import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Scale } from "lucide-react";

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and BillingEasy ("Company," "we," "us," or "our"), governed by the Indian Contract Act, 1872.

By clicking "Create Account," registering on our platform, accessing any feature, or using any part of the BillingEasy service, you unconditionally accept and agree to be bound by these Terms, our Privacy Policy, and any other policies or guidelines published by us from time to time. This act of clicking constitutes a valid offer and acceptance under Section 2(b) of the Indian Contract Act, 1872, forming a binding contract between you and BillingEasy.

If you do not agree to these Terms, you must immediately cease using the Service and delete your account. Continued use of the Service following any amendment to these Terms constitutes your acceptance of the amended Terms.

These Terms are also subject to the provisions of the Information Technology Act, 2000, the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, the Consumer Protection Act, 2019, the Consumer Protection (E-Commerce) Rules, 2020, and the Digital Personal Data Protection Act, 2023 (DPDP Act).`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `BillingEasy is an AI-powered GST billing and business management Software-as-a-Service (SaaS) platform designed for Indian businesses. The Service provides tools including but not limited to:

• GST-compliant invoice generation (GSTR-1, GSTR-3B-ready data)
• AI Bookkeeper for automated bookkeeping assistance and financial insights
• Party (customer/vendor) ledger management
• Purchase and sales order management
• Expense tracking and categorisation
• Bank statement analysis and reconciliation
• Product and inventory catalogue management
• Payment collection via QR codes and payment links
• GST reports and data exports compatible with GSTN requirements
• POS (Point of Sale) functionality for retail and restaurant businesses
• TDS computation assistance and tracking

IMPORTANT DISCLAIMER: BillingEasy is a software tool. It is NOT a Chartered Accountant (CA) firm, tax consultant, legal advisor, or financial services provider. The Service and any output generated by it — including AI-generated suggestions, reports, and recommendations — are provided for informational and operational convenience purposes only and do not constitute professional accounting, tax, legal, or financial advice. Users are strongly advised to consult a qualified Chartered Accountant or tax professional for all GST filings, tax planning, legal compliance, and financial decisions.`,
  },
  {
    id: "eligibility",
    title: "3. Eligibility",
    content: `To use the Service, you must satisfy all of the following conditions:

(a) Age: You must be at least 18 years of age. By registering, you represent and warrant that you are 18 years of age or older.

(b) Legal Capacity: You must have the full legal capacity and authority to enter into this agreement under applicable Indian law.

(c) Business Authority: If you are registering on behalf of a business entity — including a proprietorship, partnership firm, LLP, private limited company, or any other legal entity — you represent and warrant that you are duly authorised to bind that entity to these Terms and that your use of the Service is for legitimate business purposes.

(d) GST Compliance: While BillingEasy can be used by businesses at various stages of GST registration, certain features (such as GSTN-linked data) are designed for GST-registered businesses. You must ensure your GSTN details entered in the Service are accurate, current, and belong to your business.

(e) Regulatory Compliance: You must not be prohibited by any applicable law, regulation, court order, or regulatory authority from using the Service.

BillingEasy reserves the right to verify your eligibility at any time and to refuse Service or terminate accounts where eligibility requirements are not met.`,
  },
  {
    id: "account",
    title: "4. Account Registration & Security",
    content: `(a) Registration: You must provide accurate, complete, and current information during registration, including your name, email address, business name, GSTIN (if applicable), and contact details. You agree to promptly update this information to keep it accurate and current.

(b) Account Credentials: You are solely responsible for maintaining the confidentiality and security of your login credentials, including your password, OTPs, and any two-factor authentication methods. You agree not to share your credentials with any third party.

(c) Account Activity: You are fully responsible for all activities, transactions, and actions that occur under your account, whether authorised by you or not. BillingEasy shall not be liable for any loss or damage arising from unauthorised access to your account resulting from your failure to keep credentials secure.

(d) Security Breach Notification: If you suspect or become aware of any unauthorised access to, or use of, your account or any security breach, you must notify us immediately at vijayakumartech1@gmail.com. We will take reasonable steps to investigate and address the breach. You must also take immediate steps to secure your account, including changing your password.

(e) Single Account Policy: Each business entity or individual should maintain only one account. Creating multiple accounts to circumvent usage limits, credit restrictions, or any other policy is a violation of these Terms and may result in immediate termination of all associated accounts.

(f) Account Verification: BillingEasy may require you to verify your identity, email address, or mobile number at any time. Failure to complete verification within a reasonable timeframe may result in restricted access to the Service.`,
  },
  {
    id: "credits",
    title: "5. Credits System",
    content: `BillingEasy operates on a credits-based consumption model for AI-powered and advanced features. The following terms govern the use of credits:

(a) Free Credits on Signup: Every new user receives 50 (fifty) complimentary credits upon successful account creation and verification. These credits are available immediately upon registration and can be used for any credit-eligible feature within the Service.

(b) How Credits Work: Credits are consumed when you use AI-powered features such as the AI Bookkeeper, AI-generated suggestions, automated data processing, and certain advanced report generation functionalities. The number of credits consumed per action is displayed within the platform before consumption and is subject to change with prior notice.

(c) Credit Purchases: Additional credits can be purchased through the platform using our supported payment gateway (Cashfree). Credit packs are available in various denominations as displayed on the Credits/Wallet page. All credit purchases are final (see our Refund & Cancellation Policy).

(d) Credit Expiry: Credits purchased by users do not expire. Free credits issued upon signup also do not expire as long as your account remains active and in good standing. BillingEasy reserves the right to modify this policy with 30 days' prior notice to existing users.

(e) Non-Transferability: Credits are non-transferable between accounts and have no cash value. They cannot be gifted, sold, or transferred to another user or business entity.

(f) No Cash Refund for Unused Credits: Unused credits — whether free credits or purchased credits — cannot be redeemed for cash or any other form of monetary value, except in cases of technical failure as described in our Refund & Cancellation Policy.

(g) Credit Forfeiture: Upon account termination (whether voluntary or by BillingEasy for a violation), all unused credits — including purchased credits — will be forfeited without compensation.`,
  },
  {
    id: "acceptable-use",
    title: "6. Acceptable Use Policy",
    content: `You agree to use BillingEasy solely for lawful business purposes in accordance with all applicable Indian laws and regulations, including the GST Act, 2017, the Information Technology Act, 2000, and all other applicable statutes. The following activities are strictly prohibited:

(a) Illegal Use: Using the Service for any purpose that is unlawful, fraudulent, harmful, threatening, defamatory, obscene, or otherwise objectionable under Indian law.

(b) GST Fraud: Generating false, fictitious, or fraudulent GST invoices; inputting incorrect GSTIN details; using the platform to claim fraudulent Input Tax Credit (ITC); or facilitating any form of GST evasion or fraud as defined under the GST Act, 2017. Such activity may be reported to the relevant tax authorities.

(c) Reverse Engineering: Attempting to reverse engineer, decompile, disassemble, or otherwise derive the source code or underlying algorithms of the BillingEasy platform, its AI systems, or any associated software.

(d) Scraping & Automated Access: Using bots, scrapers, automated scripts, or any other automated means to access, collect, or extract data from the platform without our express written permission.

(e) Interference: Attempting to interfere with, disrupt, or compromise the integrity, security, or performance of our servers, networks, or databases, including through denial-of-service attacks, introduction of malware, or any other malicious activity.

(f) Impersonation: Impersonating any person, business, or entity, or misrepresenting your affiliation with any person or entity.

(g) Unauthorised Access: Attempting to gain unauthorised access to any part of the Service, other user accounts, or systems connected to BillingEasy.

(h) Data Misuse: Using data accessed through the Service in a manner that violates any user's privacy rights or the provisions of the DPDP Act, 2023.

Violation of this Acceptable Use Policy may result in immediate suspension or termination of your account, and BillingEasy reserves the right to report illegal activities to the appropriate law enforcement or regulatory authorities.`,
  },
  {
    id: "ip",
    title: "7. Intellectual Property",
    content: `(a) BillingEasy's Intellectual Property: All software, source code, algorithms, AI models, databases, interfaces, design elements, graphics, logos, trademarks, service marks, trade names, documentation, and content comprising or made available through the BillingEasy platform ("BillingEasy IP") are the exclusive intellectual property of BillingEasy and its licensors. All rights are reserved.

Nothing in these Terms grants you any ownership rights or licence in or to the BillingEasy IP beyond the limited, non-exclusive, non-transferable, revocable licence to use the Service for your own legitimate business purposes during the term of your subscription.

You may not copy, reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any BillingEasy IP except as permitted by these Terms.

(b) User Data Ownership: You retain full ownership of all business data, invoices, ledger entries, customer records, financial data, and other information that you input into or generate through the Service ("User Data"). BillingEasy does not claim any ownership over your User Data.

(c) Licence to BillingEasy: By using the Service, you grant BillingEasy a limited, non-exclusive, worldwide, royalty-free licence to access, process, store, and use your User Data solely for the purposes of providing, maintaining, improving, and operating the Service. This licence does not permit us to share your User Data with third parties except as described in our Privacy Policy.

(d) Feedback: If you provide feedback, suggestions, or ideas regarding the Service, you grant BillingEasy a perpetual, irrevocable, royalty-free licence to use such feedback for any purpose without any obligation to compensate you.`,
  },
  {
    id: "ai-disclaimer",
    title: "8. AI Features Disclaimer",
    content: `BillingEasy incorporates artificial intelligence and machine learning features, including the AI Bookkeeper, automated categorisation, and AI-generated financial insights. Users must understand and acknowledge the following:

(a) Guidance Only: All output generated by AI features — including categorisations, suggestions, summaries, tax estimates, reconciliation recommendations, and financial insights — is provided for general guidance and informational purposes only. It does not constitute legal advice, tax advice, accounting advice, or professional financial advice of any kind.

(b) Not a CA or Tax Professional: BillingEasy's AI systems are software tools and do not replace the services of a qualified Chartered Accountant (CA), Cost Accountant (CMA), Company Secretary (CS), advocate, or any other licensed professional. For compliance-critical decisions — including GST return filing, income tax filing, audit preparation, and financial reporting — you must consult and rely on a qualified professional.

(c) Accuracy Limitations: AI systems can make errors, produce incorrect output, or fail to account for specific business circumstances, recent legislative changes, or jurisdiction-specific nuances. BillingEasy makes no warranty or guarantee regarding the accuracy, completeness, or reliability of AI-generated output.

(d) User Verification Obligation: You are solely responsible for reviewing, verifying, and validating all AI-generated output before relying on it for any purpose, including submission to any government authority, regulatory body, or financial institution. Do not file GST returns, make tax payments, or take legally consequential actions based solely on AI output without independent professional verification.

(e) No Liability for AI Errors: BillingEasy shall not be liable for any loss, penalty, interest, demand, legal proceedings, or other consequences arising from your reliance on AI-generated output without independent verification.`,
  },
  {
    id: "gst-disclaimer",
    title: "9. GST Data Accuracy Disclaimer",
    content: `(a) User Responsibility: You, the User, are solely and exclusively responsible for the accuracy, completeness, and correctness of all GST-related data entered into the Service, including but not limited to: GSTIN details, invoice data, HSN/SAC codes, tax rates applied, place of supply, buyer and seller details, Input Tax Credit (ITC) claims, and return data.

(b) Not a Filing Service: BillingEasy is a data management and invoice generation tool. It is not a GST Suvidha Provider (GSP), GST filing service, or authorised intermediary for filing returns with the GST Network (GSTN). Any data export or report generated by BillingEasy must be independently verified by you or your tax professional before submission to GSTN or any government authority.

(c) Regulatory Changes: GST laws, rules, and rates are subject to change by the Government of India and respective State Governments. BillingEasy endeavours to keep its platform updated with regulatory changes but does not guarantee that the platform reflects the most current legal requirements at all times. You remain responsible for ensuring your filings comply with the applicable law in force at the time of filing.

(d) Penalties & Compliance: BillingEasy shall not be liable for any GST penalties, interest, late fees, prosecution, or regulatory action arising from incorrect data entry, incorrect tax rate application, incorrect ITC claims, or non-compliance with GST regulations, even if such errors were facilitated by the use of the Service.`,
  },
  {
    id: "payment",
    title: "10. Payment & Billing",
    content: `(a) Payment Gateway: All credit pack purchases on BillingEasy are processed through Cashfree Payments, a RBI-regulated payment aggregator. By making a payment, you also agree to Cashfree's terms of service and privacy policy.

(b) Currency: All transactions on BillingEasy are denominated in Indian Rupees (INR) only.

(c) GST on Purchases: Credit packs and other purchases on the platform are subject to Goods and Services Tax (GST) at 18% (nine percent CGST + nine percent SGST, or eighteen percent IGST, as applicable based on your location and the company's place of supply) under the GST Act, 2017. The applicable GST will be displayed at checkout before payment confirmation.

(d) Tax Invoices: BillingEasy will issue a valid GST tax invoice for every credit pack purchase. This invoice will be available for download from your account dashboard. You must ensure your GSTIN is correctly entered in your profile to receive a GST-compliant invoice that qualifies for ITC.

(e) Pricing Changes: BillingEasy reserves the right to change credit pack pricing at any time. Price changes will apply prospectively and will not affect credits already purchased.

(f) Payment Disputes: In the event of any payment dispute, please contact us at vijayakumartech1@gmail.com within 7 days of the transaction. Please refer to our Refund & Cancellation Policy for refund eligibility and the process.`,
  },
  {
    id: "data-ownership",
    title: "11. Data Ownership & Portability",
    content: `(a) Your Data, Your Right: You retain full and exclusive ownership of all User Data you create, input, or generate through the Service. This includes customer data, vendor data, invoices, purchase orders, expense records, ledger entries, bank statements, and all other business data.

(b) Data Export: You may export your User Data at any time while your account is active. BillingEasy provides data export functionality in standard formats (such as PDF, Excel/CSV). You are responsible for downloading and maintaining copies of your data.

(c) Data After Termination: Following account deletion or termination, BillingEasy will retain your User Data for a period of 30 (thirty) days, during which you may request a data export. After this period, your data will be permanently deleted from our active systems, subject to legal retention requirements (for example, GST records may need to be retained for the periods prescribed under applicable law).

(d) Data Security: BillingEasy implements industry-standard technical and organisational security measures to protect your User Data against unauthorised access, alteration, disclosure, or destruction. However, no method of data transmission or storage is completely secure, and BillingEasy cannot guarantee absolute security.

(e) DPDP Act Compliance: BillingEasy processes personal data in accordance with the Digital Personal Data Protection Act, 2023. For more details on how we collect, process, and protect personal data, please refer to our Privacy Policy.`,
  },
  {
    id: "availability",
    title: "12. Service Availability",
    content: `(a) Uptime Target: BillingEasy aims to maintain a platform uptime of 99.5% or higher, measured on a monthly basis, excluding scheduled maintenance windows.

(b) No SLA Guarantee: Notwithstanding the above target, BillingEasy does not provide a formal Service Level Agreement (SLA) with guaranteed uptime for the credits-based or free tier. No compensation, credit, or refund is payable for downtime unless separately agreed in writing for enterprise-tier customers.

(c) Scheduled Maintenance: BillingEasy may take the Service offline for scheduled maintenance. We will endeavour to provide advance notice of planned maintenance via email or in-app notification, typically at least 24 hours in advance for maintenance expected to exceed 30 minutes.

(d) Unplanned Downtime: In the event of unplanned outages, BillingEasy will make commercially reasonable efforts to restore the Service promptly and will communicate status updates through available channels.

(e) Third-Party Dependencies: BillingEasy's Service relies on third-party cloud infrastructure, payment gateways, and other service providers. BillingEasy shall not be liable for service disruptions caused by failures of third-party providers beyond our reasonable control.

(f) Force Majeure: BillingEasy shall not be liable for any failure or delay in performance of the Service due to causes beyond its reasonable control, including natural disasters, acts of government, power failures, internet disruptions, pandemics, strikes, or any other event of force majeure.`,
  },
  {
    id: "liability",
    title: "13. Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE INDIAN LAW:

(a) Exclusion of Consequential Damages: BillingEasy, its directors, officers, employees, agents, partners, and licensors shall not be liable to you for any indirect, incidental, special, consequential, punitive, or exemplary damages, including but not limited to: loss of profits, loss of revenue, loss of business, loss of data, loss of goodwill, or business interruption, even if BillingEasy has been advised of the possibility of such damages.

(b) Cap on Direct Liability: In all cases, BillingEasy's total aggregate liability to you for any direct damages arising out of or related to your use of the Service — whether based in contract, tort, statute, or any other legal theory — shall not exceed the total amount paid by you to BillingEasy for credits during the three (3) calendar months immediately preceding the event giving rise to the claim.

(c) Free Credits: BillingEasy's liability in respect of free credits issued upon signup shall be zero (INR 0), as no monetary consideration was paid for such credits.

(d) Reasonableness: The parties acknowledge that these limitations of liability are reasonable in light of the nature of the Service, the pricing, and the allocation of risk between the parties, and that BillingEasy would not have entered into this agreement without these limitations.

(e) Consumer Rights: Nothing in this clause shall exclude or limit any rights you may have under the Consumer Protection Act, 2019 that cannot be excluded or limited by agreement.`,
  },
  {
    id: "indemnification",
    title: "14. Indemnification",
    content: `You agree to indemnify, defend, and hold harmless BillingEasy, its directors, officers, employees, contractors, agents, licensors, and service providers from and against any and all claims, liabilities, damages, judgments, awards, losses, costs, expenses, and fees (including reasonable legal fees) arising out of or relating to:

(a) your violation of any provision of these Terms;
(b) your use or misuse of the Service;
(c) your User Data, including any claim that your User Data infringes the intellectual property rights or other rights of any third party;
(d) your violation of any applicable law, including the GST Act, 2017, the IT Act, 2000, or the DPDP Act, 2023;
(e) any fraudulent, negligent, or wilful misconduct by you or any person acting on your behalf;
(f) your violation of any third-party rights; or
(g) any GST fraud, false invoice generation, or tax evasion carried out through the platform.

BillingEasy reserves the right to assume exclusive control over the defence of any matter for which you are required to indemnify us. You agree to cooperate fully with our defence of such claims at your expense.`,
  },
  {
    id: "governing-law",
    title: "15. Governing Law & Jurisdiction",
    content: `(a) Governing Law: These Terms and any dispute, claim, or controversy arising out of or in connection with the Service, these Terms, or their subject matter or formation (including non-contractual disputes) shall be governed by and construed in accordance with the laws of India, including the Indian Contract Act, 1872, the Information Technology Act, 2000, the GST Act, 2017, and all other applicable Indian statutes and regulations.

(b) Jurisdiction: Subject to the Dispute Resolution clause below, you irrevocably submit to the exclusive jurisdiction of the courts located in Tamil Nadu, India for the resolution of any dispute arising out of or in connection with these Terms or the Service.

(c) Language: These Terms are drawn up in the English language. In the event of any conflict between an English version and any translated version, the English version shall prevail.`,
  },
  {
    id: "dispute",
    title: "16. Dispute Resolution",
    content: `In the event of any dispute, controversy, or claim arising out of or in relation to these Terms, the Service, or any breach, termination, or invalidity thereof, the parties agree to resolve it through the following process:

(a) Amicable Resolution (First Step): Either party may notify the other in writing of the dispute. Both parties shall, in good faith, attempt to resolve the dispute through direct negotiation and amicable settlement within thirty (30) days of such notice ("Amicable Resolution Period"). Most billing and service disputes can be resolved quickly by contacting us at vijayakumartech1@gmail.com.

(b) Arbitration (Second Step): If the parties are unable to resolve the dispute amicably within the Amicable Resolution Period, either party may refer the dispute to binding arbitration under the Arbitration and Conciliation Act, 1996 (as amended). The arbitration shall be conducted by a sole arbitrator mutually agreed upon by the parties, or, failing such agreement, appointed in accordance with the provisions of the Arbitration and Conciliation Act, 1996. The seat and venue of arbitration shall be Chennai, Tamil Nadu, India. The arbitration proceedings shall be conducted in English. The arbitral award shall be final and binding on both parties.

(c) Court Proceedings (Third Step): If arbitration is not applicable or the arbitral award needs enforcement, either party may approach the competent courts in Tamil Nadu, India.

(d) Consumer Forum: Nothing in this clause restricts a consumer's right to approach the appropriate Consumer Disputes Redressal Commission under the Consumer Protection Act, 2019.`,
  },
  {
    id: "termination",
    title: "17. Termination",
    content: `(a) Termination by User: You may delete your account at any time through the account settings within the Service or by sending a written request to vijayakumartech1@gmail.com. Upon account deletion, your access to the Service will be terminated. Any unused credits in your account at the time of deletion will be forfeited without refund (see Credits System clause above).

(b) Suspension or Termination by BillingEasy: BillingEasy reserves the right to suspend, restrict, or permanently terminate your account and access to the Service, with or without prior notice, in the following circumstances:
   • Violation of any provision of these Terms or our policies;
   • Fraudulent, abusive, or illegal use of the Service;
   • Engaging in activities that harm other users, third parties, or BillingEasy;
   • Non-payment of any amounts due;
   • If required by applicable law or regulatory authority; or
   • If continued provision of the Service to you poses a legal, financial, or reputational risk to BillingEasy.

(c) Effect of Termination: Upon termination, your right to access and use the Service will immediately cease. Clauses that by their nature should survive termination (including Intellectual Property, Limitation of Liability, Indemnification, and Governing Law) shall survive termination of these Terms.

(d) Data Retrieval After Termination: You are responsible for exporting your User Data before account deletion. After account deletion, BillingEasy will retain your data for 30 days as described in the Data Ownership & Portability clause, after which it will be permanently deleted.`,
  },
  {
    id: "amendments",
    title: "18. Amendments",
    content: `(a) Right to Amend: BillingEasy reserves the right to modify, update, or replace these Terms at any time to reflect changes in our Service, legal requirements, business practices, or for any other reason.

(b) Notice of Material Changes: For material changes to these Terms — including changes that significantly affect your rights or obligations — BillingEasy will provide at least thirty (30) days' advance notice. Such notice will be given by:
   • Email to the registered email address associated with your account; and/or
   • A prominent in-app notification or banner within the Service.

(c) What Constitutes a Material Change: Material changes include, but are not limited to, changes to the credits system, limitations of liability, dispute resolution procedures, or data handling practices.

(d) Non-Material Changes: Non-material changes (such as corrections of typographical errors, clarifications that do not change the substance of the Terms, or changes required by law with immediate effect) may be made without prior notice.

(e) Acceptance of Amended Terms: Your continued use of the Service after the effective date of any amended Terms constitutes your acceptance of the amended Terms. If you do not agree to the amended Terms, you must stop using the Service and delete your account before the effective date.

(f) Version History: The effective date of the current version of these Terms is displayed at the top of this page. You are encouraged to review these Terms periodically.`,
  },
  {
    id: "contact",
    title: "19. Contact & Grievance Officer",
    content: `BillingEasy is committed to addressing your concerns and grievances promptly and fairly.

For general queries, account issues, billing support, and feedback:
• Email: vijayakumartech1@gmail.com
• Website: https://billingseasy.com

Grievance Officer (as required under the Consumer Protection (E-Commerce) Rules, 2020 and the IT (Intermediary Guidelines) Rules, 2021):

Name: Vijay Kumar
Designation: Grievance Officer, BillingEasy
Email: vijayakumartech1@gmail.com
Website: https://billingseasy.com

The Grievance Officer shall acknowledge your complaint within 48 (forty-eight) hours of receipt and shall endeavour to resolve it within 30 (thirty) days of receipt, as required under applicable law.

When writing to the Grievance Officer, please include:
• Your registered email address
• A clear description of your grievance
• Relevant transaction IDs, invoice numbers, or account details
• Any supporting documentation

Please note that grievances relating to data protection or privacy concerns may also be addressed to the Data Protection Officer at the same email address.`,
  },
];

export default function Terms() {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Button>
          <div className="flex items-center gap-2">
            <Scale className="h-5 w-5 text-blue-600" />
            <span className="font-semibold text-gray-900 hidden sm:block">BillingEasy</span>
          </div>
        </div>
      </div>

      {/* Hero */}
      <div className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-10">
          <div className="flex flex-col gap-3">
            <Badge variant="outline" className="w-fit text-xs text-gray-500 border-gray-300">
              Last updated: July 4, 2026
            </Badge>
            <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">Terms of Service</h1>
            <p className="text-gray-600 text-base max-w-2xl">
              Please read these Terms carefully before using BillingEasy. They form a legally binding agreement between
              you and BillingEasy, governed by Indian law.
            </p>
            <div className="flex flex-wrap gap-2 mt-1">
              {["Indian Contract Act, 1872", "IT Act, 2000", "Consumer Protection Act, 2019", "GST Act, 2017", "DPDP Act, 2023"].map(
                (law) => (
                  <Badge key={law} variant="secondary" className="text-xs">
                    {law}
                  </Badge>
                )
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Table of Contents */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6">
        <Card className="mb-6 border border-blue-100 bg-blue-50/50">
          <CardHeader className="pb-3 pt-5">
            <CardTitle className="text-sm font-semibold text-blue-900">Table of Contents</CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-1">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="text-sm text-blue-700 hover:text-blue-900 hover:underline py-0.5"
                >
                  {section.title}
                </a>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Sections */}
        <div className="flex flex-col gap-4">
          {sections.map((section) => (
            <Card
              key={section.id}
              id={section.id}
              className="border border-gray-200 shadow-sm scroll-mt-20"
            >
              <CardHeader className="pb-3 pt-5">
                <CardTitle className="text-lg font-semibold text-gray-900">{section.title}</CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">
                  {section.content}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Footer Note */}
        <div className="mt-8 mb-10 p-5 bg-amber-50 border border-amber-200 rounded-lg">
          <p className="text-sm text-amber-800 font-medium mb-1">Important Notice</p>
          <p className="text-sm text-amber-700">
            BillingEasy is a software tool, not a Chartered Accountant firm or legal advisor. All AI-generated outputs
            are for informational purposes only. Always consult a qualified CA or tax professional for compliance-critical
            decisions. These Terms are effective from July 2026 and supersede all prior versions.
          </p>
        </div>

        <div className="text-center text-xs text-gray-400 pb-8">
          © 2026 BillingEasy. All rights reserved. |{" "}
          <a href="mailto:vijayakumartech1@gmail.com" className="hover:text-gray-600 underline">
            vijayakumartech1@gmail.com
          </a>{" "}
          |{" "}
          <a href="https://billingseasy.com" target="_blank" rel="noopener noreferrer" className="hover:text-gray-600 underline">
            https://billingseasy.com
          </a>
        </div>
      </div>
    </div>
  );
}
